import { test } from 'node:test';
import { strict as assert } from 'node:assert';
import bs58 from 'bs58';
import { createReceiptJournal } from './pendingReceipt';
// Offline storage fault injection only; synthetic bytes are not signed/provider evidence.
const scope='https://api.devnet.solana.com';
const owner='BKaeJqmmgMTFAkTwUwBceLpGwpSRKfjc9TC8kvb6ieRP';
const signature=bs58.encode(new Uint8Array(64).fill(1));
const otherSignature=bs58.encode(new Uint8Array(64).fill(2));
function storage(initial:string|null=null){let value=initial;return{get:async()=>value,set:async(v:string)=>{value=v;},clear:async()=>{value=null;}};}
const prior=JSON.stringify({version:1,scope,owner,signature});
test('reload restores original unresolved hash and blocks submit',async()=>{const s=storage(prior);await assert.rejects(createReceiptJournal(s).run(scope,owner,async sig=>{assert.equal(sig,signature);return null;},async()=>assert.fail()),/unresolved/);assert.equal(await s.get(),prior);});
test('processed errors and absent commitment cannot unlock retry',async()=>{for(const r of [{err:{InstructionError:[0,1]},confirmationStatus:'processed'},{err:{InstructionError:[0,1]}},{err:null,confirmationStatus:'processed'}])await assert.rejects(createReceiptJournal(storage(prior)).run(scope,owner,async()=>r,async()=>assert.fail()),/unresolved/);});
test('missing error field cannot be interpreted as success',async()=>{await assert.rejects(createReceiptJournal(storage(prior)).run(scope,owner,async()=>({confirmationStatus:'finalized'} as any),async()=>assert.fail()),/unresolved/);});
test('RPC rejection preserves journal',async()=>{const s=storage(prior);await assert.rejects(createReceiptJournal(s).run(scope,owner,async()=>{throw Error('offline');},async()=>assert.fail()),/offline/);assert.equal(await s.get(),prior);});
test('prior terminal success refuses resubmit and asks refresh',async()=>{const s=storage(prior);await assert.rejects(createReceiptJournal(s).run(scope,owner,async()=>({err:null,confirmationStatus:'finalized'}),async()=>assert.fail()),/Previous transaction confirmed/);assert.equal(await s.get(),null);});
test('only committed chain error permits deliberate new attempt',async()=>{const s=storage(prior);await assert.rejects(createReceiptJournal(s).run(scope,owner,async()=>({err:{InstructionError:[0,1]},confirmationStatus:'confirmed'}),async save=>{await save(otherSignature);throw Error('new confirmation unavailable');}),/new confirmation unavailable/);assert.equal(JSON.parse((await s.get())!).signature,otherSignature);});
test('another wallet or network blocked before status request',async()=>{const j=()=>createReceiptJournal(storage(prior));await assert.rejects(j().run('http://localhost:8899',owner,async()=>assert.fail(),async()=>assert.fail()),/another network/);await assert.rejects(j().run(scope,'Ftk563Wp1tdf5U1nyzF1BQwShvKPdHT9VY1FKGWo8ftE',async()=>assert.fail(),async()=>assert.fail()),/another wallet/);});
test('corrupt record fields fail closed',async()=>{for(const raw of ['{bad','null',JSON.stringify({version:1,scope,owner,signature:'invalid'}),JSON.stringify({version:1,scope,owner:'bad',signature})])await assert.rejects(createReceiptJournal(storage(raw)).run(scope,owner,async()=>assert.fail(),async()=>assert.fail()),/unreadable/);});
test('known local signature survives transport failure and reload',async()=>{const s=storage();await assert.rejects(createReceiptJournal(s).run(scope,owner,async()=>null,async save=>{await save(signature);throw Error('timeout');}),/timeout/);await assert.rejects(createReceiptJournal(s).run(scope,owner,async()=>null,async()=>assert.fail()),/unresolved/);});
test('lost storage write prevents transmission continuation',async()=>{let sent=false;await assert.rejects(createReceiptJournal({get:async()=>null,set:async()=>{},clear:async()=>{}}).run(scope,owner,async()=>null,async save=>{await save(signature);sent=true;}),/intent was not saved reliably/);assert.equal(sent,false);});
test('storage exception prevents transmission continuation',async()=>{let sent=false;await assert.rejects(createReceiptJournal({get:async()=>null,set:async()=>{throw Error('keystore');},clear:async()=>{}}).run(scope,owner,async()=>null,async save=>{await save(signature);sent=true;}),/keystore/);assert.equal(sent,false);});
test('different returned hash cannot overwrite original',async()=>{const s=storage();await assert.rejects(createReceiptJournal(s).run(scope,owner,async()=>null,async save=>{await save(signature);await save(otherSignature);}),/differs from the original/);assert.equal(JSON.parse((await s.get())!).signature,signature);});
test('lost clear does not permit another submission',async()=>{const s={get:async()=>prior,set:async()=>{},clear:async()=>{}};await assert.rejects(createReceiptJournal(s).run(scope,owner,async()=>({err:{InstructionError:[0,1]},confirmationStatus:'finalized'}),async()=>assert.fail()),/could not be cleared reliably/);});
test('invalid input identity and signature rejected',async()=>{await assert.rejects(createReceiptJournal(storage()).run(scope,'bad',async()=>null,async()=>assert.fail()),/identity is invalid/);await assert.rejects(createReceiptJournal(storage()).run(scope,owner,async()=>null,async save=>save('not-a-signature')),/invalid transaction signature/);});
test('concurrent signing request rejected before second submit',async()=>{let release!:()=>void;const wait=new Promise<void>(r=>{release=r;});const j=createReceiptJournal(storage());const first=j.run(scope,owner,async()=>null,async save=>{await save(signature);await wait;throw Error('interrupted');});await assert.rejects(j.run(scope,owner,async()=>null,async()=>assert.fail()),/already in progress/);release();await assert.rejects(first,/interrupted/);});

test('pre-submit unsigned intent survives response loss and restart',async()=>{const s=storage();await assert.rejects(createReceiptJournal(s).run(scope,owner,async()=>null,async(_save,control)=>{control.beginBroadcast();throw Error('wallet response lost');}),/wallet response lost/);assert.equal(JSON.parse((await s.get())!).stage,'intent');await assert.rejects(createReceiptJournal(s).run(scope,owner,async()=>assert.fail(),async()=>assert.fail()),/before a signature was saved/);});
test('post-broadcast lost signature save retains unsigned intent',async()=>{const original=storage();let writes=0;const s={get:original.get,clear:original.clear,set:async(v:string)=>{writes++;if(writes===1)await original.set(v);}};await assert.rejects(createReceiptJournal(s).run(scope,owner,async()=>null,async(save,control)=>{control.beginBroadcast();await save(signature);}),/not saved reliably/);assert.equal(JSON.parse((await s.get())!).stage,'intent');await assert.rejects(createReceiptJournal(s).run(scope,owner,async()=>assert.fail(),async()=>assert.fail()),/before a signature was saved/);});
test('callee proof of no broadcast allows verified intent cleanup',async()=>{const s=storage();await assert.rejects(createReceiptJournal(s).run(scope,owner,async()=>null,async(_save,control)=>{assert.equal(await control.abortBeforeBroadcast(),true);throw Error('local validation');}),/local validation/);assert.equal(await s.get(),null);});
test('callee cannot clear intent after broadcast began',async()=>{const s=storage();await assert.rejects(createReceiptJournal(s).run(scope,owner,async()=>null,async(_save,control)=>{control.beginBroadcast();assert.equal(await control.abortBeforeBroadcast(),false);throw Error('interrupted');}),/interrupted/);assert.notEqual(await s.get(),null);});
