/**
 * Bake the 3D arena's procedural textures for the native app.
 *
 *   cd mobile && npx tsx scripts/bake-textures.ts
 *
 * The web arena draws grass, water, wood, sky, particle sprites and the unit
 * mask on a canvas at runtime (app/src/three/textures.ts, vfx.ts, unitMask.ts).
 * React Native has no canvas, so this runs those exact generators in Node
 * against @napi-rs/canvas and writes each one as a PNG, plus the require() map
 * the native canvas backend (app/src/three/canvasTex.native.ts) looks names up
 * in. Every generator is seeded, so the output is deterministic: rerunning the
 * script on unchanged sources produces identical files.
 */
import { createCanvas } from '@napi-rs/canvas';
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { baked, setCanvasFactory } from '../../app/src/three/canvasTex';
import * as tex from '../../app/src/three/textures';
import { softDot, sparkDot } from '../../app/src/three/vfx';
import { makeAlphaMask } from '../../app/src/three/unitMask';

const OUT = join(__dirname, '..', 'assets', 'baked');

setCanvasFactory((w, h) => createCanvas(w, h) as unknown as HTMLCanvasElement);

tex.grassTexture();
tex.woodTexture();
tex.waterTexture();
tex.causticTexture();
tex.stoneTexture();
tex.meadowTexture();
tex.skyTexture();
tex.cloudTexture();
tex.sandTexture();
tex.masonryTexture();
softDot();
sparkDot();
makeAlphaMask();

const names = [...baked.keys()].sort();
for (const name of names) {
  const c = baked.get(name) as unknown as ReturnType<typeof createCanvas>;
  writeFileSync(join(OUT, `${name}.png`), c.toBuffer('image/png'));
  console.log(`baked ${name}.png ${c.width}x${c.height}`);
}

writeFileSync(join(__dirname, '..', 'src', 'arena', 'baked.ts'), [
  '// Generated by scripts/bake-textures.ts — do not edit by hand.',
  '/* eslint-disable */',
  'export const BAKED: Record<string, number> = {',
  ...names.map((n) => `  ${JSON.stringify(n)}: require('../../assets/baked/${n}.png'),`),
  '};',
  '',
].join('\n'));
