/**
 * Bake the 3D arena's procedural textures for the native app.
 *
 *   cd mobile && npx tsx scripts/bake-textures.ts
 *
 * The web arena draws grass, water, wood, sky, particle sprites and the unit
 * mask on a canvas at runtime (app/src/three/textures.ts, vfx.ts, unitMask.ts).
 * React Native has no canvas, so this runs those exact generators in Node
 * against @napi-rs/canvas and writes each one as a PNG, plus the require() map
 * the native canvas backend (app/src/three/canvasTex.native.ts) looks names up
 * in. Every generator is seeded, so the output is deterministic: rerunning the
 * script on unchanged sources produces identical files.
 */
import { createCanvas } from '@napi-rs/canvas';
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { baked, setCanvasFactory } from '../../app/src/three/canvasTex';
import * as tex from '../../app/src/three/textures';
import { softDot, sparkDot } from '../../app/src/three/vfx';
import { makeAlphaMask } from '../../app/src/three/unitMask';
import { ARENA_SKIN_IDS, SKINNED_TEXTURES, recolor } from '../../app/src/three/skin';

const OUT = join(__dirname, '..', 'assets', 'baked');

setCanvasFactory((w, h) => createCanvas(w, h) as unknown as HTMLCanvasElement);

tex.grassTexture();
tex.woodTexture();
tex.waterTexture();
tex.causticTexture();
tex.stoneTexture();
tex.meadowTexture();
tex.skyTexture();
tex.cloudTexture();
tex.sandTexture();
tex.masonryTexture();
softDot();
sparkDot();
makeAlphaMask();

const baseNames = [...baked.keys()].sort();
for (const name of baseNames) {
  const c = baked.get(name) as unknown as ReturnType<typeof createCanvas>;
  writeFileSync(join(OUT, `${name}.png`), c.toBuffer('image/png'));
  console.log(`baked ${name}.png ${c.width}x${c.height}`);
}

// Arena skins: the same pixels, recoloured per skin (app/src/three/skin.ts).
const variants: string[] = [];
for (const skin of ARENA_SKIN_IDS) {
  if (skin === 'default') continue;
  for (const name of SKINNED_TEXTURES) {
    const src = baked.get(name) as unknown as ReturnType<typeof createCanvas> | undefined;
    if (!src) continue;
    const ctx = src.getContext('2d');
    const img = ctx.getImageData(0, 0, src.width, src.height);
    const d = img.data;
    for (let i = 0; i < d.length; i += 4) {
      const [r, g, b] = recolor(skin, d[i], d[i + 1], d[i + 2]);
      d[i] = r; d[i + 1] = g; d[i + 2] = b;
    }
    const out = createCanvas(src.width, src.height);
    out.getContext('2d').putImageData(img, 0, 0);
    const v = `${name}__${skin}`;
    writeFileSync(join(OUT, `${v}.png`), out.toBuffer('image/png'));
    variants.push(v);
  }
}
console.log(`baked ${variants.length} skin variants`);
const names = [...baseNames, ...variants].sort();

writeFileSync(join(__dirname, '..', 'src', 'arena', 'baked.ts'), [
  '// Generated by scripts/bake-textures.ts — do not edit by hand.',
  '/* eslint-disable */',
  'export const BAKED: Record<string, number> = {',
  ...names.map((n) => `  ${JSON.stringify(n)}: require('../../assets/baked/${n}.png'),`),
  '};',
  '',
].join('\n'));
