#!/usr/bin/env node
/**
 * Generate the native app's roster and art map from the game's own data.
 *
 * The native screens (collection, deck, shop, chest reveals) render the same
 * fighters the 3D battle uses. Rather than hand-copy a list that would drift,
 * this reads the registry the web client and the on-chain program agree on
 * (`app/src/lib/devnet-coins.json`) plus the card catalogue (asset class), and
 * writes:
 *
 *   src/data/roster.json   ticker, name, devnet mint, hue, kind
 *   src/data/art.ts        static require() map Metro can bundle
 *   assets/game/*.webp     the card / chest / icon art (same bytes as app/public)
 *
 *   node scripts/gen-roster.mjs
 */
import { execFileSync } from 'node:child_process';
import { copyFileSync, existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const MOBILE = join(HERE, '..');
const APP = join(MOBILE, '..', 'app');
const ART = join(APP, 'public', 'art');
const OUT_ART = join(MOBILE, 'assets', 'game');
mkdirSync(OUT_ART, { recursive: true });

const registry = JSON.parse(readFileSync(join(APP, 'src/lib/devnet-coins.json'), 'utf8'));
const catalogue = JSON.parse(readFileSync(join(APP, 'src/data/cards.json'), 'utf8'));
const kind = new Map(catalogue.cards.map((c) => [c.ticker.toUpperCase(), c.kind]));

const roster = [];
for (const c of registry.coins) {
  const file = `card_${c.ticker.toLowerCase()}.webp`;
  if (!existsSync(join(ART, file))) continue; // no fighter art, no native card
  copyFileSync(join(ART, file), join(OUT_ART, file));
  roster.push({
    ticker: c.ticker, name: c.name, mint: c.mint, hue: c.hue,
    kind: kind.get(c.ticker.toUpperCase()) ?? 'meme',
    eligible: c.liquidityUsd >= 25_000,
  });
}

const EXTRA = [
  'logo', 'avatar_guest', 'chest_silver', 'chest_golden', 'chest_magic', 'chest_legendary',
  'chest_open', 'icon_tank', 'icon_swarm', 'icon_ranged', 'icon_splash', 'icon_support',
  'icon_spell', 'tab_arena', 'tab_cards', 'tab_deck', 'tab_empire', 'tab_swap', 'clan_badge',
  'wood_seamless', 'arena_ground',
];
for (const e of EXTRA) copyFileSync(join(ART, `${e}.webp`), join(OUT_ART, `${e}.webp`));

// Cards are drawn on magenta; key it out once here (the web does it on a canvas).
execFileSync('python3', [join(HERE, 'key-art.py'), OUT_ART], { stdio: 'inherit' });

// PNG copies for the native 3D arena (expo-gl cannot decode WebP).
execFileSync('python3', [join(HERE, 'unit-png.py'), OUT_ART, join(MOBILE, 'assets', 'units')], { stdio: 'inherit' });
writeFileSync(join(MOBILE, 'src/arena/unitArt.ts'), [
  '// Generated by scripts/gen-roster.mjs — PNG unit sprites for the native arena.',
  '/* eslint-disable */',
  'export const UNIT_ART: Record<string, number> = {',
  ...roster.map((r) => `  ${JSON.stringify(r.ticker)}: require('../../assets/units/unit_${r.ticker.toLowerCase()}.png'),`),
  '};',
  "export const UNIT_FALLBACK = require('../../assets/units/avatar_guest.png');",
  '',
].join('\n'));

writeFileSync(join(MOBILE, 'src/data/roster.json'), `${JSON.stringify(roster, null, 1)}\n`);
const lines = [
  '// Generated by scripts/gen-roster.mjs — do not edit by hand.',
  '/* eslint-disable */',
  'export const CARD_ART: Record<string, number> = {',
  ...roster.map((r) => `  ${JSON.stringify(r.ticker)}: require('../../assets/game/card_${r.ticker.toLowerCase()}.webp'),`),
  '};',
  'export const UI_ART = {',
  ...EXTRA.map((e) => `  ${e}: require('../../assets/game/${e}.webp'),`),
  '} as const;',
  '',
];
writeFileSync(join(MOBILE, 'src/data/art.ts'), lines.join('\n'));
console.log(`roster: ${roster.length} fighters, ${EXTRA.length} ui images`);
