// Generated by scripts/bake-textures.ts — do not edit by hand.
/* eslint-disable */
export const BAKED: Record<string, number> = {
  "caustic": require('../../assets/baked/caustic.png'),
  "cloud": require('../../assets/baked/cloud.png'),
  "grass": require('../../assets/baked/grass.png'),
  "masonry": require('../../assets/baked/masonry.png'),
  "meadow": require('../../assets/baked/meadow.png'),
  "sand": require('../../assets/baked/sand.png'),
  "sky": require('../../assets/baked/sky.png'),
  "stone": require('../../assets/baked/stone.png'),
  "unit-mask": require('../../assets/baked/unit-mask.png'),
  "vfx-dot": require('../../assets/baked/vfx-dot.png'),
  "vfx-star": require('../../assets/baked/vfx-star.png'),
  "water": require('../../assets/baked/water.png'),
  "wood": require('../../assets/baked/wood.png'),
};
